name: 'My First GitHub Actions Workflow'

on: push

jobs:
  fist-job:
    name: 'first Job'
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    runs-on: ${{ matrix.os }}

    steps:
      - name: 'Say Hello on ${{ matrix.os }}'
        shell: bash
        run: |
          echo "Hello from ${{ matrix.os }}"
